# Generated by Django 5.0.3 on 2024-03-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "example",
            "0002_fund_acab_fund_animal_fund_domicile_fund_gge_fund_gs_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="fund",
            old_name="gs",
            new_name="cannabis",
        ),
    ]
